require 'rubygems'
require 'bundler/setup'
Bundler.require
require 'rspec/core/rake_task'

Dir[File.dirname(__FILE__) + '/lib/*.rb'].each { |file| require file }

task :default => :spec
RSpec::Core::RakeTask.new(:spec)

desc 'Run the simulation'
task :run, :steps, :size, :pattern do |_, args|
  args.with_defaults :steps => 20,
                     :size => 20,
                     :pattern => :glider

  options = { :steps => args.steps.to_i,
              :size => args.size.to_i,
              :pattern => args.pattern }

  Board.new(options).run!
end

desc 'Run the game with a specific pattern. Defaults to glider'
task :pattern, :pattern do |_, args|
  args.with_defaults(:pattern => :glider)

  Rake::Task[:run].invoke(20, 20, args.pattern)
end
