require 'rubygems'
require 'bundler/setup'
Bundler.require
require 'rspec/core/rake_task'

Dir[File.dirname(__FILE__) + '/lib/*.rb'].each { |file| require file }

task :default => :spec
RSpec::Core::RakeTask.new(:spec)

namespace :game do
  desc 'Run the simulation'
  task :run, [:steps, :size] do |_, args|
    args.with_defaults(:steps => 10, :size => 20)

    options = { :steps => args.steps.to_i,
                :size => args.size.to_i }

    Board.new(options).run!
  end
end
